# Generated by Django 5.1.2 on 2024-11-06 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0011_time_alter_loanrequest_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Percentage_Profit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Percentage_profit', models.CharField(max_length=250)),
                ('Time_limit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_limit', to='loanApp.time')),
            ],
        ),
    ]
